export type Locale = 'en' | 'zh';

export const LOCALE_STORAGE_KEY = 'kumo-demo-locale';

export const localeMeta = {
  en: {htmlLang: 'en', shortLabel: 'EN', switchLabel: '切换到中文'},
  zh: {htmlLang: 'zh-CN', shortLabel: '中', switchLabel: 'Switch to English'},
} as const;

export const uiCopy = {
  en: {
    navigationGroup: 'Navigation',
    loading: 'Loading...',
    accountMenu: 'Account menu',
    openUserCenter: 'Open user center',
    collapseNavigation: 'Collapse navigation',
    toggleTheme: 'Toggle theme',
    notificationsLabel: 'Notifications',
    dark: 'Dark',
    light: 'Light',
    noPage: 'No page configuration found.',
    closePage: 'Close',
    auth: {
      nameRequired: 'Enter your name to create an account.',
      emailInvalid: 'Enter a valid email address.',
      passwordShort: 'Password must be at least 6 characters.',
      failed: 'Authentication failed. Please try again.',
      registerTitle: 'Create an account',
      loginTitle: 'Sign in',
      registerDescription: 'Create an account to access the admin console',
      loginDescription: 'Use the demo account to access the admin console',
      name: 'Name',
      email: 'Email',
      password: 'Password',
      registerAction: 'Create account',
      loginAction: 'Sign in',
      hasAccount: 'Already have an account?',
      newHere: 'New here?',
    },
    notifications: {
      title: 'Notifications',
      markAllRead: 'Mark all as read',
      read: 'Read',
      unread: 'Unread',
      empty: 'No notifications',
      close: 'Close',
    },
    dashboard: {
      loading: 'Loading dashboard...',
      empty: 'No dashboard data',
      title: 'Dashboard',
      refresh: 'Refresh data',
      trendTitle: '12-month business trend',
      months: '12 months',
      barChart: 'Bar',
      lineChart: 'Line',
      actualValue: 'Actual',
      targetValue: 'Target',
      distribution: 'Module distribution',
      capacity: 'capacity',
      activity: 'System activity',
      latest: 'Latest updates',
    },
    resource: {
      select: 'Select',
      enter: 'Enter',
      name: 'Name',
      required: 'Complete all required fields before saving.',
      saveFailed: 'Save failed. Please try again.',
      export: 'Export',
      addNew: 'Add new',
      all: 'All',
      search: 'Search',
      reset: 'Reset',
      ascending: 'ascending',
      descending: 'descending',
      records: 'Records',
      loading: 'Loading...',
      record: 'record',
      recordsPlural: 'records',
      perPage: 'per page',
      actions: 'Actions',
      edit: 'Edit',
      delete: 'Delete',
      noResults: 'No matching results',
      noResultsHint: 'Adjust your filters and try again.',
      pagination: 'Pagination',
      firstPage: 'First page',
      previousPage: 'Previous page',
      nextPage: 'Next page',
      lastPage: 'Last page',
      pageNumber: 'Page number',
      pageSize: 'Items per page',
      showing: 'Showing',
      of: 'of',
      perPageLabel: 'Per page',
      add: 'Add',
      cancel: 'Cancel',
      save: 'Save',
      deleteTitle: 'Delete record',
      deleteDescription: 'This record will be removed from the list immediately.',
      viewTags: 'View all',
      tags: 'tags',
    },
    userCenter: {
      title: 'User center',
      editTitle: 'Edit profile',
      avatar: 'Avatar',
      avatarHint: 'Upload a square profile image. It will update the sidebar avatar after saving.',
      chooseAvatar: 'Choose image',
      name: 'Name',
      jobTitle: 'Job title',
      department: 'Department',
      manager: 'Manager',
      email: 'Email',
      phone: 'Phone',
      enterpriseWechat: 'Enterprise WeChat',
      emergencyContact: 'Emergency contact',
      location: 'Office location',
      status: 'Status',
      cancel: 'Cancel',
      save: 'Save',
      securityTitle: 'Security settings',
      dismiss: 'Dismiss',
      done: 'Done',
      loading: 'Loading user center...',
      profileSaveFailed: 'Could not save the profile. Please try again.',
      securitySaveFailed: 'Could not save security settings. Previous settings were restored.',
      offlineStatus: 'Offline',
      busyStatus: 'Busy',
      editProfile: 'Edit profile',
      securitySettings: 'Security settings',
      profileDetails: 'Profile details',
      contactDetails: 'Contact details',
      sendEmail: 'Send email',
      callPhone: 'Call phone',
      organization: 'Organization',
    },
  },
  zh: {
    navigationGroup: '导航',
    loading: '正在加载...',
    accountMenu: '账号菜单',
    openUserCenter: '打开用户中心',
    collapseNavigation: '折叠导航',
    toggleTheme: '切换主题',
    notificationsLabel: '通知中心',
    dark: '深色',
    light: '浅色',
    noPage: '暂无页面配置。',
    closePage: '关闭',
    auth: {
      nameRequired: '请输入姓名后再注册。',
      emailInvalid: '请输入有效的邮箱地址。',
      passwordShort: '密码至少需要 6 位。',
      failed: '认证失败，请重试。',
      registerTitle: '注册账号',
      loginTitle: '登录账号',
      registerDescription: '创建账号后进入后台管理系统',
      loginDescription: '使用演示账号进入后台管理系统',
      name: '姓名',
      email: '邮箱',
      password: '密码',
      registerAction: '注册并进入',
      loginAction: '登录',
      hasAccount: '已有账号？',
      newHere: '还没有账号？',
    },
    notifications: {
      title: '通知中心',
      markAllRead: '全部已读',
      read: '已读',
      unread: '未读',
      empty: '暂无通知',
      close: '关闭',
    },
    dashboard: {
      loading: '正在加载工作台...',
      empty: '暂无工作台数据',
      title: '首页',
      refresh: '刷新数据',
      trendTitle: '近 12 月业务趋势',
      months: '12 个月',
      barChart: '柱状图',
      lineChart: '折线图',
      actualValue: '实际',
      targetValue: '目标',
      distribution: '模块占比',
      capacity: '容量',
      activity: '系统动态',
      latest: '最近更新',
    },
    resource: {
      select: '选择',
      enter: '输入',
      name: '名称',
      required: '请补全必填项后再保存。',
      saveFailed: '保存失败，请重试。',
      export: '导出',
      addNew: '新增',
      all: '全部',
      search: '查询',
      reset: '重置',
      ascending: '升序',
      descending: '降序',
      records: '数据列表',
      loading: '正在加载...',
      record: '条记录',
      recordsPlural: '条记录',
      perPage: '每页',
      actions: '操作',
      edit: '编辑',
      delete: '删除',
      noResults: '没有匹配结果',
      noResultsHint: '调整筛选条件后重试。',
      pagination: '分页',
      firstPage: '第一页',
      previousPage: '上一页',
      nextPage: '下一页',
      lastPage: '最后一页',
      pageNumber: '页码',
      pageSize: '每页数量',
      showing: '显示',
      of: '共',
      perPageLabel: '每页',
      add: '新增',
      cancel: '取消',
      save: '保存',
      deleteTitle: '删除记录',
      deleteDescription: '删除后当前列表会立即更新。',
      viewTags: '查看全部',
      tags: '个标签',
    },
    userCenter: {
      title: '用户中心',
      editTitle: '编辑资料',
      avatar: '头像',
      avatarHint: '上传方形头像图片，保存后会同步更新左下角头像。',
      chooseAvatar: '选择图片',
      name: '姓名',
      jobTitle: '岗位',
      department: '所属部门',
      manager: '直属上级',
      email: '邮箱',
      phone: '手机号',
      enterpriseWechat: '企业微信',
      emergencyContact: '紧急联系人',
      location: '办公地点',
      status: '当前状态',
      cancel: '取消',
      save: '保存',
      securityTitle: '安全设置',
      dismiss: '关闭',
      done: '完成',
      loading: '正在加载用户中心...',
      profileSaveFailed: '资料保存失败，请重试。',
      securitySaveFailed: '安全设置保存失败，已恢复原设置。',
      offlineStatus: '离线待命',
      busyStatus: '忙碌处理中',
      editProfile: '编辑资料',
      securitySettings: '安全设置',
      profileDetails: '基本资料',
      contactDetails: '联系方式',
      sendEmail: '发送邮件',
      callPhone: '拨打电话',
      organization: '组织身份',
    },
  },
} as const;
